# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design4.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 562)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tab2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tab2.setObjectName("tab2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.upload = QtWidgets.QPushButton(self.tab)
        self.upload.setObjectName("upload")
        self.verticalLayout.addWidget(self.upload)
        self.image = QtWidgets.QLabel(self.tab)
        self.image.setText("")
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.verticalLayout.addWidget(self.image)
        self.noise = QtWidgets.QComboBox(self.tab)
        self.noise.setObjectName("noise")
        self.noise.addItem("")
        self.noise.addItem("")
        self.noise.addItem("")
        self.verticalLayout.addWidget(self.noise)
        self.noisy_image = QtWidgets.QLabel(self.tab)
        self.noisy_image.setText("")
        self.noisy_image.setScaledContents(True)
        self.noisy_image.setObjectName("noisy_image")
        self.verticalLayout.addWidget(self.noisy_image)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.filter = QtWidgets.QComboBox(self.tab)
        self.filter.setObjectName("filter")
        self.filter.addItem("")
        self.filter.addItem("")
        self.filter.addItem("")
        self.horizontalLayout_2.addWidget(self.filter)
        self.edge = QtWidgets.QComboBox(self.tab)
        self.edge.setObjectName("edge")
        self.edge.addItem("")
        self.edge.addItem("")
        self.edge.addItem("")
        self.edge.addItem("")
        self.horizontalLayout_2.addWidget(self.edge)
        self.equalize = QtWidgets.QPushButton(self.tab)
        self.equalize.setObjectName("equalize")
        self.horizontalLayout_2.addWidget(self.equalize)
        self.normalize = QtWidgets.QPushButton(self.tab)
        self.normalize.setObjectName("normalize")
        self.horizontalLayout_2.addWidget(self.normalize)
        self.gray_scale = QtWidgets.QPushButton(self.tab)
        self.gray_scale.setObjectName("gray_scale")
        self.horizontalLayout_2.addWidget(self.gray_scale)
        self.freq_filter = QtWidgets.QComboBox(self.tab)
        self.freq_filter.setObjectName("freq_filter")
        self.freq_filter.addItem("")
        self.freq_filter.addItem("")
        self.horizontalLayout_2.addWidget(self.freq_filter)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.image_result = QtWidgets.QLabel(self.tab)
        self.image_result.setText("")
        self.image_result.setScaledContents(True)
        self.image_result.setObjectName("image_result")
        self.verticalLayout_2.addWidget(self.image_result)
        self.histogram = QtWidgets.QComboBox(self.tab)
        self.histogram.setObjectName("histogram")
        self.histogram.addItem("")
        self.histogram.addItem("")
        self.verticalLayout_2.addWidget(self.histogram)
        self.graph = PlotWidget(self.tab)
        self.graph.setMaximumSize(QtCore.QSize(16777215, 210))
        self.graph.setObjectName("graph")
        self.verticalLayout_2.addWidget(self.graph)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tab2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.hybrid = QtWidgets.QPushButton(self.tab_2)
        self.hybrid.setGeometry(QtCore.QRect(290, 60, 52, 23))
        self.hybrid.setObjectName("hybrid")
        self.input1 = QtWidgets.QLabel(self.tab_2)
        self.input1.setGeometry(QtCore.QRect(30, 90, 201, 181))
        self.input1.setText("")
        self.input1.setScaledContents(True)
        self.input1.setObjectName("input1")
        self.upload1 = QtWidgets.QPushButton(self.tab_2)
        self.upload1.setGeometry(QtCore.QRect(40, 30, 181, 31))
        self.upload1.setObjectName("upload1")
        self.upload2 = QtWidgets.QPushButton(self.tab_2)
        self.upload2.setGeometry(QtCore.QRect(50, 290, 161, 31))
        self.upload2.setObjectName("upload2")
        self.input1_2 = QtWidgets.QLabel(self.tab_2)
        self.input1_2.setGeometry(QtCore.QRect(270, 260, 201, 181))
        self.input1_2.setText("")
        self.input1_2.setScaledContents(True)
        self.input1_2.setObjectName("input1_2")
        self.tab2.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tab2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.upload.setText(_translate("MainWindow", "PushButton"))
        self.noise.setItemText(0, _translate("MainWindow", "uniform noise"))
        self.noise.setItemText(1, _translate("MainWindow", "gaussian noise"))
        self.noise.setItemText(2, _translate("MainWindow", " salt_and_pepper noise"))
        self.filter.setItemText(0, _translate("MainWindow", "average filter"))
        self.filter.setItemText(1, _translate("MainWindow", "gaussian filter"))
        self.filter.setItemText(2, _translate("MainWindow", "median filter"))
        self.edge.setItemText(0, _translate("MainWindow", "sobel edge detector"))
        self.edge.setItemText(1, _translate("MainWindow", "roberts edge detector"))
        self.edge.setItemText(2, _translate("MainWindow", "prewitt edge detector "))
        self.edge.setItemText(3, _translate("MainWindow", "canny edge detector"))
        self.equalize.setText(_translate("MainWindow", "equalize"))
        self.normalize.setText(_translate("MainWindow", "normalize"))
        self.gray_scale.setText(_translate("MainWindow", "gray scale"))
        self.freq_filter.setItemText(0, _translate("MainWindow", "HPF"))
        self.freq_filter.setItemText(1, _translate("MainWindow", "LPF"))
        self.histogram.setItemText(0, _translate("MainWindow", "histogram"))
        self.histogram.setItemText(1, _translate("MainWindow", "R,G,B histogram"))
        self.tab2.setTabText(self.tab2.indexOf(self.tab), _translate("MainWindow", "image"))
        self.hybrid.setText(_translate("MainWindow", "hybrid"))
        self.upload1.setText(_translate("MainWindow", "Upload image"))
        self.upload2.setText(_translate("MainWindow", "Upload image"))
        self.tab2.setTabText(self.tab2.indexOf(self.tab_2), _translate("MainWindow", "hybrid"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

